personal_Blog/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace personal_Blog.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

personal_Blog/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace personal_Blog.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }
    public void OnGet()
    {

    }
    //[TempData]
    //public string ?Role {  get; set; }
    public IActionResult OnPostGoAsSeller()
    {
        HttpContext.Session.SetString("Role", "vendeur");
        //Role = HttpContext.Session.GetString("Role");
        if(User.Identity.IsAuthenticated)
        {
            return Redirect("/PagesNote/Index");
        }
        else
        {
            HttpContext.Session.SetString("Role", "vendeur");
            return Redirect("/Identity/Account/Login?returnUrl=/PagesNote/Index");
        }

        //return Redirect("/Identity/Account/Login");
    }
    public IActionResult OnPostGoAsClient() 
    {
        //Role = "client";
        HttpContext.Session.SetString("Role", "client");
        return RedirectToPage("/PagesNote/Index");
    } 
}

personal_Blog/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace personal_Blog.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

personal_Blog/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>blog</title>
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
    <div class="banner">
        <div class="navbar">
            <img src="/images/logo_2.jpg" class="logo" alt="">
        </div>
        <div class="content">
            <h1>FIND YOUR HOME</h1>
            <p>Here you can find the details of your dream home <br>(Avenue, district, street, contact number)</p>
            <div>
                <form method="post">
                    <button type="submit" asp-page-handler="GoAsClient">
                        <span></span>I am a customer
                    </button> 

                    <button type="submit" asp-page-handler="GoAsSeller">
                        <span></span>I am a seller
                    </button>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

<!--
<html xmlns="http://www.w3.org/1999/xhtml">
    <head><title></title></head>
    <body>
        <div class="text-center">
            <h1 class="display-4">Bienvenu sur le Blog</h1>
            <h2>Je suis un Client</h2>
            <h2>Je suis un Vendeur</h2>
            <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
        </div>

    </body>
</html>-->